### ISSUE TITLE
Layers with dynamic opacity are not rendering correctly in Kibana

### ISSUE THREAD

**Issue by jsanz** [elastic/osm-bright-gl-style#11]
There is a significant and noticeable mismatch in how Kibana renders the OSM Bright style (called `Roadmap` or `Classic`).

| Kibana | EMS Landing Page |
| :--:   | :--: |
| ![image](https://github.com/elastic/osm-bright-gl-style/assets/188264/6a17079b-72ce-4e48-af9d-5145910d8135) | ![image](https://github.com/elastic/osm-bright-gl-style/assets/188264/91b81cf9-d070-4950-8ddd-e2127215ca53) |

The underlying issue is that Kibana tries to parse the opacity of a layer to assign the setting from the interface (starting with a default value of `100%`) but fails to understand the mapbox style spec using stops so it defaults to move the layer transparency to `100%`. I did some testing to try to fix this at Kibana, but removing all dynamic opacity from our basemap styles makes more sense to avoid edge cases or unwanted effects.

This issue is also affecting light and dark styles to a lesser extent but yet I've opened PRs for all styles, removing dynamic opacity.

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/osm-bright-gl-style/pull/12
- [ ] https://github.com/elastic/osm-bright-desaturated-gl-style/pull/10
- [ ] https://github.com/elastic/dark-matter-gl-style/pull/6
```

**Comment by jsanz** [comment]
THis is is an issue on how Kibana re-assigns opacity to basemap layers. I will open a PR in Kibana to try to address this, but keeping this open in case the issue needs to be resolved by removing dynamic `fill-opacity` on `landcover-wood` and `landcover-glacier`.

**Comment by jsanz** [comment]
On this GIF the issue can be perceived in the dark style and `landcover-glacier` that is present in Greenland at low zoom levels.

![Peek 2023-10-03 19-15](https://github.com/elastic/osm-bright-gl-style/assets/188264/0010c341-602d-4dad-bc78-324131d9e598)

**Comment by jsanz** [comment]
Given that Kibana will always overwrite layers' opacity by the application settings, it makes no sense to keep dynamic opacity on any styles so I need to review the three of them and replace any dynamic opacity with something static, very likely modifying colors by zoom level or similar.

**Comment by jsanz** [comment]
@nickpeihl I've just tagged you on three separate PRs for all three styles. I've put the source of the issue here for reference.

**Comment by jsanz** [comment]
Closing this as finished, next step is to work in the Elastic infra to get these news styles.
